baseurl = "https://checkintmn.ru/"
languageCode = "ru-RU"
title = "Фотопрогулки по Тюмени - Check in TMN"

[params]
  description = "Фотосъёмка для портфолио, семейного альбома, lovestory в формате прогулки с фотографом по Тюмени"
  author = "Екатерина Квитова и Евгений Кувшинов"
  keywords = "фотосъёмка, фотограф, фотопрогулка, тюмень"
  locale = "ru-RU"

[taxonomies]
tag = "tags"